### ISSUE TITLE
24. [18:02:27] [INFO] 〢 Total Time Taken = 2 seconds --> Less time but returns NONE.

### ISSUE THREAD

**Issue by Seila123457** [kokiez/hcaptcha-solver#10]
1. 1. [18:19:00] [DEBUG] 〢 [ * ] SOLVING...
2. [18:19:00] [DEBUG] 〢 [ * ] Question: Please click each image containing a rough ѕea
3. [18:19:00] [DEBUG] 〢 [ * ] Modified Label: rough sea
4. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 1, Result: True
5. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 2, Result: True
6. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 3, Result: False
7. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 4, Result: False
8. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 5, Result: False
9. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 6, Result: False
10. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 7, Result: False
11. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 8, Result: True
12. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 9, Result: True
13. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 10, Result: False
14. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 11, Result: False
15. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 12, Result: False
16. [18:19:01] [DEBUG] 〢 [ + ] Image Number: 13, Result: True
17. [18:19:02] [DEBUG] 〢 [ + ] Image Number: 14, Result: True
18. [18:19:02] [DEBUG] 〢 [ + ] Image Number: 15, Result: True
19. [18:19:02] [DEBUG] 〢 [ + ] Image Number: 16, Result: False
20. [18:19:02] [DEBUG] 〢 [ + ] Image Number: 17, Result: True
21. [18:19:02] [DEBUG] 〢 [ + ] Image Number: 18, Result: True
22. [18:19:02] [DEBUG] 〢 [ + ] Solving Captcha by Choosing Images Now.
23. [18:19:02] [DEBUG] 〢 [ - ] Captcha solved but wrong, Retrying...
24. Token value: None

every time I run the program it's returning the captchas like this, can you help me?

**Comment by kokiez** [comment]
https://github.com/kokiez/hcaptcha-solver/blob/main/modules/hcaptcha/challenges.py

add a time.sleep(seconds) between line number 128 and 129 
or increase the one at 131

**Comment by Seila123457** [comment]
1. [00:22:05] [INFO]  〢 Total Time Taken = 16 seconds
2. [00:22:05] [ ERROR ]  〢 Captcha Error, Retrying...
3. [00:22:05] [INFO]  〢 3 Proxy Selected:
4. [00:22:05] [DEBUG] 〢 [ * ] SOLVING...
5. [00:22:16] [DEBUG] 〢 [ * ] Question: Please click each image containing a һedgehog
6. [00:22:16] [DEBUG] 〢 [ * ] Modified Label: hedgehog
7. [00:22:16] [INFO]  〢 [ + ] AI not trained for this captcha type yet !
8. Run the Download_Update.bat to check for updates
9. [00:22:16] [DEBUG] 〢 [ + ] Solving Captcha by Choosing Images Now.
11. [00:22:21] [DEBUG] 〢 [ - ] Captcha solved but wrong, Retrying...
12. Token value: None

dont fix

**Comment by kokiez** [comment]
did you download the models ?

**Comment by Seila123457** [comment]
1. [19:46:54] [INFO]  〢 2 Proxy Selected:
2. [19:46:54] [DEBUG] 〢 [ * ] SOLVING...
3. [19:47:05] [DEBUG] 〢 [ * ] Question: Please click each image containing a rough seа
4. [19:47:05] [DEBUG] 〢 [ * ] Modified Label: rough sea
5. [19:47:05] [DEBUG] 〢 [ + ] Image Number: 1, Result: False
6. [19:47:05] [DEBUG] 〢 [ + ] Image Number: 2, Result: False
7. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 3, Result: True
8. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 4, Result: False
9. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 5, Result: True
10. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 6, Result: False
11. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 7, Result: False
12. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 8, Result: True
13. [19:47:06] [DEBUG] 〢 [ + ] Image Number: 9, Result: True
14. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 10, Result: True
15. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 11, Result: False
16. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 12, Result: True
17. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 13, Result: True
18. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 14, Result: False
19. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 15, Result: False
20. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 16, Result: False
21. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 17, Result: True
22. [19:47:07] [DEBUG] 〢 [ + ] Image Number: 18, Result: False
23. [19:47:07] [DEBUG] 〢 [ + ] Solving Captcha by Choosing Images Now.
24. P0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiVVRQNC9OTTdDYVlXTm5oUjhTWkdVSWZKSDlCdTVLeUNQRXNqSlROUm5zZU43ZHpqcjBYdS9QVzJYVVExN1AvRWNvTFhnTExaS1duZVBnM2s0c2JuaUJ1Kzc2cWQvcjF6VE9jaGk1SXhvMGZyczdCNW5pQ1NZMzRqdXZJblcydEtNY3VMT3JjbkVpb3pVSHcyTFlIZzhlR3lDZXAySXpWTE0xb0VRMEFaYW1zSGdkN2NLa0Q5Z1g0bThaTVNoMnM2NGRUZnpFSW1XVUR4ZC8vTExBcklPSTBQKzdrck9sTUc3c3NYTy9DaTBzbmpncnFSZGkrTU9pWE10dGx1RnQvTGFwRm1mZ3M4ZVFoYVh2dVQ5aERKWGs1ZjBuTlVCZi8zYUVMWnhCMUE1TGQ2b0E2aCtnQU5udFl5YVQvU0NXVytSaEYzRG1kU09WeEFiNU9mL0hSZmVJNFRFSUROVmtxdlRpcHBPbnZZSFdHQkJ4bFFkenlFT0VCNHpZc1UvOENDSHFjNk85R2JVazg0UUt6Z1VYOHd1OVFDdk8wWFovMGs1UDk1L0lES2QzM2ZYeW53YTUzek1nL00xQm1aNFAxMXhKcThIZjlYeWFzTUpmV1k5TCt5dTRlWDZDYXRVTlBuY0ducnZsTEllVFhMd3VJYlVPbTBnaVZxZlRMQk1DWFliZ1JlS0UzbGI0Wk83REk2bW9ESDNkbkdjZjJGK3U0QzdjMURZRTlxUzM5UmJtZmdqanJ1ZTVSR2pEVmQzOTBTTC9TSkRiSVNkRFhKQW94VHhFa1gwcTUvZDJhemdiVVVLQUthalpFRTBxWjhJNGh4YzFGQ2trNDlqWndHYUpucExQTCtxclVGUFRrLzNqYS9PWUxsYnBEcDJndzB5UllvaTVxVEFXVW5weGttVlc0dTI3N1F0YVhwb0RFNG1kYUgwYW1HTE1uaWpqRm9peEYxTmxmR215Zmt4OTFadDdmRTZwZ29FRHhLOCtIQ0JTYTVCcU42cW41VTQyTmMraURCdEpjRFYvbU1kR2VuUm9qbE5WOXE4TS9LNTRUK3FZalF1YU80ZCt1TnU2VmV5OWFCK3IvSTlqblBheEc3V0ZvQVlZaUtDVC9qbUp2ZVA1UEg2ejRYeENSVmlNYVdkYk1FeHZhUGVENDMvT09SVStLT3YyakhtWkhLV0pOK0RYbkJDRzFaWG5NdkhqZlI3Y1ArellWTWsxb0tNRis4dzZKVUVqdll2WTg3dmZqZElCcVVaYU5IUmI3QVpUUWlKZ2J5SGExRGI5TnNCbzFxRk9ZKy9iMFA0d2FkUTBlV0YzaTc1V09aeUREK0RXOUk3T2ZXN0tFZ0tPMlJwYnZUbnQwd0tHZmNOS0FRRG9Yb0Zyc2pMempUa2pwLytNN1dXdHNEL212KzJpblViVDFKcG9NSVN3NDhITWVyYU0waExMS0c4amZyVit4N2lWKzFpaDNhRWxDdWJJSzBUMnpjOWxKaHF5RnBja2tybVZTYnZTY1BGbHJMVkE3UENmU0NZbm5mYUZRSjhFdXBxSExOMUkrWlVKNTFIeWF3N01YNFprcHc4OExtMjU4S0F1ckpoZ2RRaFhFczUvVGVuaHVWSmxHOExYWW9SWnIwTStNcFAvV0VyRE5HOVBVWlpYRDRvZ0ZWeFArNUFaNnFZYWpjaDFkcmQycVF2TE9hd0VsdVdRM1Z4Q2RsMThna2J4c0RMOVhCeEtPNWIrV1llWUZPY2xBaytGbjZWSFd6RUFQK21XTE9Ya1lTRDRBQnhvWE1vUjZhd0ErdkxxYWxkZkJmUFVkS0RkYzV2UFcrTTlmRU56b0w0ZGRqMTkvenBGV0EvWEFMWGc3UWlpdzJCemlHN0cyMEhPbUUzWVN0SThyeTZZTHBMVVdWaitkQ0FvME12Y0Qxa2xWOFlDMUZaZHVBMlFIdDVneW5IdmxKTWc3QVErYmFZUjBUbTlpNmI0NkhnTU85Zk5rbklnYlpRZmcwYWd5YlFuVFdWUms2VURkdk9xYlNkVm1LY3NEc2J6ZUZ1ZTJYeTQ4b0NqQm5UVCtGa29NcW9XVmc3b3U0V2RuZm9EVmZoanVtMjhXUkE0aUFuS0VVQjNWRHFJeW8yZVhNSTFEV3dVTjlJUGViOVJqaCtpOHh6OEN0dStWRmlwQzFZWXhKMi8vRXVtMlNBNnJuelF1eGRhSklZRE5FdzZtNXpCQjRIU0N3VnJKaXdCcmlRbHVwMWV5R0JPajEyNTUyMVVGcEdxakJjUGNwRHA0cXluY0JJR09YTWJQM01CdWYxKzRObHZoYytmdTlHcmtDOUVMOGMzZUtSMjVDVzhHTEJmU2dYKzhBSDZmZUxCemNPUEI5b3RqRFd3cXU5SURMemZTV3JqSS9EZ0xwM1JKT2RDcmVObzZjMHRpcWZkSmozY1d1UHBLZkMyUitLYjZJUWdybXBjaElubkVkVi84c29aWk9rbTBxUlB4WnQyWmJ5aXp5WDNtQVZ0cjdMdWhlUVdJT3kycHBuTzdOSzMwM250UHQxTGRtazJDVE1DT1VpMHIya1NLQTNaSHRsaWg0UEo4Q3ZSVUgxOUVMZXJUeXZ4WUpLbEZBYXhqSGJUUXVQNWE4eUdKemtxV3Ewd3dNWTdMZ1Y3ZnhYVEhjOExMZGFxN21PL2Q2KzhhTlRxME1neE5NYkRwUzJ2MWQzeDZ6WHZ1clBmWmhEK2VJcWpQb25ocWpLRXlOQ3hmcUVRQ3dEbEYwdGZBOENNQXcwWDliYThsYXNybFFJcDc3aDRRTFhBS282SDZjQjZOdGlvSkpHNmhXOGRHVjcvekkvMFdwbGVuVzc4OENFS1VLWVF2TWRmU00yd3hlUzExbDRhS3BDcitxdWNyTFg5WjlJRWxwRExSeDNaekZ5ai92ZDdSSVoyaytNZG1hdUtEaFRHNXVrTWg0a3BwU2t3czZ4MTZQVHhSRytuVmNLV1ZudWp3bTk4VFNKWStVMFlITzBnNnZyM05JYkp2dzNxcTNMY2lvSkdmSXoxTmdEMDJWNkNwb09oai9FM015SkFBd1p3bEl0ME5TdElFdEYyV0JsNFlOSkNCQng3TTdHbFhVK1hMcXlGOE5CTnRvWW5SWVkzanFLdTNWRlhHd1RoN0c5ZVpwNnYzNk1KYVBTKzZ1ck1JbTNBUFVycGtMb0J2Ky9qenJrNHpFU3ZqQ1o5WkliY1Ewc005QnlJeFdOYnE4UzNvWFd4dEZqa3Fhc0ozK3YrRzZuVkR5Y3lFZzFEdU9CTTF0Y0l5ZENlQzVjejh3VFowTnFEa002RUp0ejV0aFhqazhJNUM4MVRZSDdkNUtaZmx5TTFpUnZRcnhQSncvdUtmUTEzbnpwWlg0cDU3bi9BeGZKOHk0MithL3hPUjIydlNQOHBIQ2NJU3RzcWVPNGltQ3B6UGNjMUFmQ1l3cXNKMTVDUWdnNkhjOUFXYnpRa1liYlpmdmlraFVGbGxCMy9MVC9iNGROSHl3ekxSN2xKMVpjUHp6SHJxWHc0T2J3V0pwY3VtNm4weTRMVk43MVZiNFMwQnp0NHAzdjVJOERtZGFJZm4yMWdhNWVGWjdEejZGRllhTGs1Q0EzTERHZSs1eWZuZ01Dd1piaHJrRkl6R0VUbEdqbE5iQjlqZHIyTENpd3RWZmtodTRFMS8vNW5yUXV3OXR0eGQxUEE5dDZ3QVhNd0hES2tseDR2akVUUjNScEI5citMQjJPeGZWQnVFb2dRNEYyemtWNmhXTG9mdFpObUpjYlpxTi9lUXlhVlIxclRQVHZOOHAyQVRJMVhSdDlEaE9PdVBaZTVqTHFSUExubXdJandaeUtKSHB6U1RNK1dDRThBLzBaY25rditCdmNueHU5dFRLejJERmRaOUM4VitETEpvMEJnMDV4WGFRU3Bodk54ZkZMMFdTWU9aR3BMRm5waUl3YktxQUozVE1PYmZLZ3ZCYS8rQmxpUTMvdDRHMmpwQldONS9uWkp3QjF0a1hWaUw4NGdLQkpsZTNXM1Y3VFNJM2UyREpOOW54ZXc5QllSSnlqNVFjRDlYMitEQ2V3dTJEUW9MRHQ5QXBuaFVMK1lNVjFLK3grWlRxN1pBbWhWYm1Cc3ZrNHZ4OWl4aStMK3QzVWkxNlhnRjhCb1pKZ1ZWNDlOMVpSeE1iZGlkMGJaUkdFQWtZTWtjdWk2emlDQ0s0R0NTQjJuemtIL3k1NFdFbWR6aVRPZm4zc1drdktZeWhUUjNRTmlQWXQxT2FzdGdsdWZYNnhsM0NiVXQ5ZkUrZXVYZlpPdkQvOFA0RnBmQlkzMjdKYWhHTEJQdVh5aHJibmJIZXU3WkRLZGRISUlqRGQzOWhXY2pmTzNJRFJEUG9xQ3QyOHEveTNrcW1DR3J2eFFCaFBXenM0RlVlWnhQQnFZVDh4VmhnSG5kd1F4RkRoNjRFOUw4Z3EwRmJsVEUxaVRWZEtYaUVpK3VrTkVtTEJqb0JRWmhkZzVCOE41a0NLM2lKdXJ3Z2F4bXB1b296UmJ6emczVVg2OEhWcjN0aDdvSXdXbmNsbFFxdmltL3puUEtwcWE0U2w2eFJVZERpRmxHbEQ3N29OMVhldTZSWEZkUHRabDM4cnJ2MFE4VTkvNUtEQ2VDazFuU3R5VURhaEd0Q2pKWG5XdVE2NTdTTlJ2dlcyVG1YMm9DKzFETUx5MXo1MThKNlBZbDh4ekswWmNCZS80UXVjSUVXaEdiaWVwTUlGWUpBVTIySkkrNjUyTU1PSTRLNUM4NzN1R013WkoyL0lGdXhTeUpaQi82L204akl3V2JWZzNBNGJibXI4aGVCSE11LzdybkxHUG5EM3c3OHpTWmx6cWY5cC9KWU1WL20xM0dYWWJ0RVl1WHMzMFd1ODFUcEI5M1VXYlFocmZLdERUcUtGVFd2ZzNUVm1JdTEzTUdqTFQ0OCtPa0s1U1Q3VG4rLytncEdZdGkyZkFzTUQyV2hPQ2ZrenFVTk5ZMVlFL2FIM0QzUUpDbTN0VkxXMUpISm1oYjN6c3l2bGVnd0x1enJXWTE3MFl1cUJpSkhBeHp5dzdWMDJ0NTcxZThyMk16OWtydHFDQnZHMG1pcER6c091UzJYT3ZJWExLNjRjV29jUDZuV2NGQVVYNGpxVG1ZRm5YM21lbkRNTGkxMXkzWGtyR21FS3l3Qm9aYlY3L2t6bzg3cnluZlFndWpvRSszME1ZbWoxRCtHbTEyU2dKTW51MVY2UVJnRGRWUG02K1VBV0FJTXRFTHdiMHVZUkd0SVpZN1BVTVQ0RjRiNm9TRkp6UURBSHBrYzFneHFwZFJLakRLL2Vac1BIcXhVVzJHSHJVWWlIQnB3OXg2b09mYi9vVkhpWm93b21KNnVvb2VNRFdkNjd1L2tTeDQwWFVBekd2WEtiTHJTc0R5WDhlUzI5Z0lEK2t6WGpUQ05XY0R4Ny9mR09OazF1NlpkdjJENXRIcjhyTnhOVEJ5d01GeTZEV2ZmYUFLRS9ibzF4emJPVXdxeUg3MGI0cTI5RnpMa05zRVB6b3BScEMwdzI1K0w3dlZ0V05adVZ1NGtOYzN6NWVmTjNQNGFvVzlnYVNkcFBEUnNPa0ZUektBalprN2lLQk5vTmcwOGNmbjB6Z0RBeUI0eVNaVnNEY0dnNUI5dGFBQXMyanI2SnhBODNaalB3NmY5dEpsREtuTE53bExlKzlyUW5XQ0dWUnhMQUJSTjhrYzRzT2pnbXlvOEUyNEFTaUxKRllOV0dPWmZqRU4wOUhHV1p5aHViNmNvVlY1MnhWQ3pBS2lEbE1CV2NnV0lCQVBnMGg3YlBaRkZsQlptb08va0JTajE4MUY2OUdWZ0oyaGkvUkR6OHY0eTA3MkRoeUNqOGFWMzI0Qkpzem1JRStFbDZtVUVxNzYyQ2lWQVlSOHlqTEU3S1RIUXZtSExWcFJUcmZoQmU3QkZHMDlvZkFjanB4VFlPbVBSL3BYUnZOZCthdmdqdFMxOEpIV2lBK3JXbDlQSzVaR1E0cEFUMytGRXBMU2I0Qkd5UDhjMkRGQWNiSjRnRDFHdStqRWNjbkRGWllNT0NyN2hVeHJCWGYwemZPd25kRVBhR3RodUsyYTdNc2U5aU4zZDB6L0V4UVU4djg2RDQwOGFtMXh2dG4vaHhma0Z3c2V6U0lQTWNSTUM5YUw2OTdtQjV4Mkw3NU1EMnRWWmpNMHJMeXRCVEQ4WkpPNVdWaVdyWGw3QThuK1dDVWl1ak85QnY5dlYwTElKUmo0dnRFVlBabXMxRjhQQy9CSGhTY1RCelhhYzNKNGpBaGlJRWNrPUlwSHpBTnBEUURpbGJMeTUiLCJleHAiOjE2Njk1Nzg1NTMsInNoYXJkX2lkIjo1MzU3NjU1OSwicGQiOjB9.4gi6ZbMudKsm5x24M_VjV2RL6p4VNQvvd785jNtf2TI
25. [19:47:13] [INFO]  〢 Total Time Taken = 18 seconds


I had already downloaded the templates, but I transferred them again and now it works! ty bro
