### ISSUE TITLE
Captcha needs retry very often

### ISSUE THREAD

**Issue by marl0nx** [kokiez/hcaptcha-solver#4]
I know u said u didnt find any other models. But could u add like PyTorch (pb format) support so u can train models by yourself easily? Or could u provide a url for a tutorial how to train already existing onnx files (if possible)

**Comment by DsCookieMaster** [comment]
**But could u add like PyTorch (pb format) support so u can train models by yourself easily?**  
Thanks for sharing, I will work on it after 9th November.

**Or could u provide a url for a tutorial how to train already existing onnx files (if possible)**
you can find that by yourself using google/youtube. The onnx models are generated using yolov (Check references of QIN2DIM)

**Comment by kokiez** [comment]
Pb format models. google, youtube, github. Learn it on your own.  Ez.

**Not working on hcaptcha solver anymore**
Since there are tons of other similar projects.
