### ISSUE TITLE
Main.py - error

### ISSUE THREAD

**Issue by reactiver001** [kokiez/hcaptcha-solver#9]
Hello i try use your script but have this error when try run main.py
windows server 2019

python main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hcaptcha-solver\main.py", line 2, in <module>
    from modules.captcha import CaptchaSolver
ModuleNotFoundError: No module named 'modules.captcha'; 'modules' is not a package

**Comment by kokiez** [comment]
repo works. Problem is with your OS.
